//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by test_urs_resource.rc
//

#define FREEEIDEALH2_HUG_CFG 120
#define FREEEIDEALH2_HUG_TEST 121
#define FREEEIDEALH2_ISOT_CFG 122
#define FREEEIDEALH2_ISOT_TEST 123
#define ABUEXPFITBR5_HUG_CFG 124
#define ABUEXPFITBR5_HUG_TEST 125
#define ABUEXPFITBR5_ISOE_CFG 126
#define ABUEXPFITBR5_ISOE_TEST 127
#define ABUSTEEL_HUG_CFG 128
#define ABUSTEEL_HUG_TEST 129
#define ABUSTEEL_ISOE_CFG 130
#define ABUSTEEL_ISOE_TEST 131
#define FREEEH2ELECTRON_HUG_CFG 132
#define FREEEH2ELECTRON_HUG_TEST 133
#define FREEEH2ELECTRON_ISOT_CFG 134
#define FREEEH2ELECTRON_ISOT_TEST 135
#define FREEEMETHCOLD_HUG_CFG 136
#define FREEEMETHCOLD_HUG_TEST 137
#define FREEEMETHCOLD_ISOT_CFG 138
#define FREEEMETHCOLD_ISOT_TEST 139
#define FREEEROSSH2DISGOOD_ISOT_CFG 140
#define FREEEROSSH2DISGOOD_ISOT_TEST 141
#define FREEEROSSN2HE1_ISOT_CFG 142
#define FREEEROSSN2HE1_ISOT_TEST 143
#define FREEEROSSN2VCOOL_ISOT_CFG 144
#define FREEEROSSN2VCOOL_ISOT_TEST 145
#define FREEEROSSN2XE1_ISOT_CFG 146
#define FREEEROSSN2XE1_ISOT_TEST 147
#define GASONEATOM_HUG_CFG 148
#define GASONEATOM_HUG_TEST 149
#define GASONEATOM_ISOE_CFG 150
#define GASONEATOM_ISOE_TEST 151
#define HISCHBR4_HUG_CFG 152
#define HISCHBR4_HUG_TEST 153
#define HISCHBR4_ISOE_CFG 154
#define HISCHBR4_ISOE_TEST 155
#define IVLPOLYSTERENE_HUG_CFG 156
#define IVLPOLYSTERENE_HUG_TEST 157
#define IVLPOLYSTERENE_ISOE_CFG 158
#define IVLPOLYSTERENE_ISOE_TEST 159
#define MO_BUSHMAN_HUG_CFG 160
#define MO_BUSHMAN_HUG_TEST 161
#define MO_BUSHMAN_ISOT_CFG 162
#define MO_BUSHMAN_ISOT_TEST 163
#define MURNAGANGEKS_HUG_CFG 164
#define MURNAGANGEKS_HUG_TEST 165
#define MURNAGANGEKS_ISOE_CFG 166
#define MURNAGANGEKS_ISOE_TEST 167
#define NI_BUSHMAN_HUG_CFG 168
#define NI_BUSHMAN_HUG_TEST 169
#define NI_BUSHMAN_ISOT_CFG 170
#define NI_BUSHMAN_ISOT_TEST 171
#define VANDERVALSN2_HUG_CFG 172
#define VANDERVALSN2_HUG_TEST 173
#define VANDERVALSN2_ISOT_CFG 174
#define VANDERVALSN2_ISOT_TEST 175
#define XESTR1_ISOT_CFG 176
#define XESTR1_ISOT_TEST 177
#define ZUBAREVGEKS_HUG_CFG 178
#define ZUBAREVGEKS_HUG_TEST 179
#define ZUBAREVGEKS_ISOE_CFG 180
#define ZUBAREVGEKS_ISOE_TEST 181

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 182
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 102
#endif
#endif
