#ifndef __MATT_CFG_H
#define __MATT_CFG_H

#include "lib\std\util.h"
#define Matter_Register


#endif


//#define InternalPointsUrs // explosive CLC
//#define MatterH2Liq_Register
//#define MatterUrl_Register
//#define MatterSpline_Register
//#define FreeE_Register
//#define FreeE_RossRegister
//#define MatterABuExp_Register
//#define MatterHisch_Register
//#define INTERNAL_FUNC  // now calculate DisDegree in matter.spl
//#define Pc_ABU_ZERO

//#define RossDiameter  //   temp thing, look RossPacking Fracture  for different temp

//#define FreeE_BushmanRegister
