      REAL FUNCTION X02ABE(X)
C     NAG COPYRIGHT 1975
C     MARK 4.5 RELEASE
      REAL X, Z
*SELF,IF=R01.
       DATA Z/Z00100000/
*SELF,IF=R04.
*     DATA Z/0001 4000 0000 0000 0000B/
*SELF.
C     * RMIN *
C     RETURNS THE VALUE OF THE SMALLEST POSITIVE REAL FLOATING-
C     POINT NUMBER EXACTLY REPRESENTABLE ON THE COMPUTER
C     THE X PARAMETER IS NOT USED
      X02ABE = Z
      RETURN
      END
